### ISSUE TITLE
Error: can't copy 'doc/man/send_osc.1': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by stefets** [mididings/pyliblo#2]
Hi, 

I try to build pyliblo and eventually mididings on Python (3.11.3 and 3.12) on Linux Mint 21.1

I have install **just** and **cargo** but there is an error : **can't copy 'doc/man/send_osc.1': doesn't exist or not a regular file**

(python3.12) stefets@live1:~/src/pyliblo$ python3.12 -m build --wheel
* Creating venv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29, setuptools>=65, wheel>=0.38)
* Getting build dependencies for wheel...
Compiling src/liblo.pyx because it depends on /tmp/build-env-n3q048ou/lib/python3.12/site-packages/Cython/Includes/libc/string.pxd.
[1/1] Cythonizing src/liblo.pyx
running egg_info
writing pyliblo.egg-info/PKG-INFO
writing dependency_links to pyliblo.egg-info/dependency_links.txt
writing requirements to pyliblo.egg-info/requires.txt
writing top-level names to pyliblo.egg-info/top_level.txt
reading manifest file 'pyliblo.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc/build'
adding license file 'COPYING'
writing manifest file 'pyliblo.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_py
running egg_info
writing pyliblo.egg-info/PKG-INFO
writing dependency_links to pyliblo.egg-info/dependency_links.txt
writing requirements to pyliblo.egg-info/requires.txt
writing top-level names to pyliblo.egg-info/top_level.txt
reading manifest file 'pyliblo.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc/build'
adding license file 'COPYING'
writing manifest file 'pyliblo.egg-info/SOURCES.txt'
running build_ext
building 'liblo' extension
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/build-env-n3q048ou/include -I/usr/include/python3.12 -c src/liblo.c -o build/temp.linux-x86_64-cpython-312/src/liblo.o -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
src/liblo.c: In function ‘__pyx_f_5liblo__extract_args’:
src/liblo.c:4323:33: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 4323 |   for (__pyx_v_i = 0; __pyx_v_i < __pyx_t_2; __pyx_v_i++) {
      |                                 ^
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto build/temp.linux-x86_64-cpython-312/src/liblo.o -L/usr/lib/x86_64-linux-gnu -llo -o build/lib.linux-x86_64-cpython-312/liblo.cpython-312-x86_64-linux-gnu.so
running build_scripts
copying and adjusting scripts/send_osc -> build/scripts-3.12
copying and adjusting scripts/dump_osc -> build/scripts-3.12
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
copying build/lib.linux-x86_64-cpython-312/liblo.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
running install_data
error: can't copy 'doc/man/send_osc.1': doesn't exist or not a regular file

ERROR Backend subprocess exited when trying to invoke build_wheel

Any advice why the man page does not exists ? 

Thanks!

**Comment by grawlinson** [comment]
Cargo isn’t used, did you mean scdoc? As that is what’s used to generate the man pages.

**Comment by stefets** [comment]
Thanks a lot @grawlinson !

I didn't think about this scdc at all and now it compile fine on my python 3.11.3
